# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 195cd8d92b6fe1134ba5f56795ab99607285029fefdf0ab1107bf91290b1c372dab915f5ede3edf88419be9d4a3a70d3e222680739315efe26bfcfcd470581f3

test:
  secret_key_base: dd6e0bbd88c8592f7474b7512bdc910aadcc1bc401f93238bb3dbcd07aac8a82a8f364cc514bee5e58e0b3db513312709fabd0118b0998684b8aa24721d49653

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
